AWSTemplateFormatVersion: '2010-09-09'
Description: 'Flask Service'

Parameters:
  TaskDefinitionArn:
    Type: String
    Description: ARN of the ECS Task Definition

Resources:
  FlaskAppService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !ImportValue MyECSClusterName
      TaskDefinition: !Ref TaskDefinitionArn
      DesiredCount: 2
      LaunchType: 'FARGATE'
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnetId
          SecurityGroups:
            - !ImportValue MySecurityGroup
          AssignPublicIp: 'ENABLED'
