AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Task Definition and Service for Flask App using Port 5000'

Parameters:
  DBPassword:
    Description: 'Database password'
    Type: 'String'
    NoEcho: true
  FlaskEnv:
    Description: 'Flask environment (development2 or development1)'
    Type: 'String'
    Default: 'development2'

Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow HTTP access to Flask app'
      VpcId: !ImportValue MyVPCID  # Ensure MyVPCID is correctly exported in a different stack
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: 5000
          ToPort: 5000
          CidrIp: '0.0.0.0/0'

  FlaskAppTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'flask-app-task'
      NetworkMode: 'awsvpc'
      RequiresCompatibilities:
        - 'FARGATE'
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: !ImportValue TaskExecutionRoleArn  # Ensure TaskExecutionRoleArn is exported correctly
      TaskRoleArn: !ImportValue MyTaskExecutionRoleExportName  # Ensure MyTaskExecutionRoleExportName is exported
      ContainerDefinitions:
        - Name: 'flask-app-container'
          Image: !ImportValue ECRRepositoryURI  # Ensure ECRRepositoryURI is exported correctly
          PortMappings:
            - ContainerPort: 5000
              Protocol: 'tcp'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: '/ecs/flask-app-service'
              awslogs-region: !ImportValue AWS_REGION
              awslogs-stream-prefix: 'ecs'
          Environment:
            - Name: 'FLASK_ENV'
              Value: !ImportValue FlaskEnv
            - Name: 'DB_USER'
              Value: 'DB_Admin'
            - Name: 'DB_PASSWORD'
              Value: !ImportValue DB_PASSWORD
            - Name: 'DB_HOST'
              Value: !ImportValue RDSInstanceEndpoint  # Ensure RDSInstanceEndpoint is exported correctly
            - Name: 'DB_PORT'
              Value: '5432'
            - Name: 'DB_NAME'
              Value: 'moviemaking_dev'
          # Uncomment Secrets for production environments if needed
          # Secrets:
          #   - Name: 'DB_PASSWORD_DEV'
          #     ValueFrom: "arn:aws:secretsmanager:eu-west-1:123456789012:secret:DB_PASSWORD_DEV"
          #   - Name: 'SECRET_KEY'
          #     ValueFrom: "arn:aws:secretsmanager:eu-west-1:123456789012:secret:SECRET_KEY"

  FlaskAppService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !ImportValue MyECSClusterName  # Ensure MyECSClusterName is exported correctly
      TaskDefinition: !Ref FlaskAppTaskDefinition
      DesiredCount: 2
      LaunchType: 'FARGATE'
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnetId  # Ensure PublicSubnetId is exported correctly
          SecurityGroups:
            - !Ref MySecurityGroup
          AssignPublicIp: 'ENABLED'
