name: Lint Markdown Files

on:
  push:
    branches: [ "dev" ]
    paths:
      - '**/*.md'  # Trigger only for changes to .md files
  pull_request:
    branches: [ "dev" ]
    paths:
      - '**/*.md'  # Trigger only for .md files in PRs
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Verify Node.js Version
        run: node --version

      - name: Navigate to Subdirectory
        run: cd Lab2 && npm install  # Change this to your actual subdirectory path if needed

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md'
