name: Markdown Lint Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Navigate to Subdirectory
        run: cd Lab2 && npm install  # Change this to your actual subdirectory path if needed

      - name: Install dependencies and markdownlint
        run: |  
         cd Lab2 
         npm install
         npm install -g markdownlint-cli

      - name: Run markdownlint
        run: npm test
