name: Build & Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.md'  # Trigger only for changes to .md files
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.md'  # Trigger only for .md files in PRs
  workflow_dispatch:


jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          audience: sts.amazonaws.com

      - name: Test AWS Connectivity
        run: aws s3 ls
